apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-app
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
        - name: golang-kube
          image: aguila95/golang-app:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: mypvc-v
              mountPath: /usr/src/app
      volumes:
        - name: mypvc-v
          persistentVolumeClaim:
            claimName: mypvc