apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/erickaja/infotec/docker-nomina-core/payroll
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: manual
  volumeName: mypv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi