apiVersion: v1
kind: Service # Defines the type of Kubernetes object, which is a Service
metadata:
  name: golang-loadbalancer # The name of the Service
spec:
  type: NodePort # The type of Service, which exposes the service on each Node's IP at a static port
  selector:
    app: golang-app # Selects the pods with the label "app: golang-app"
  ports:
    - protocol: TCP # The protocol used by the Service, which is TCP
      port: 8000 # The port that the Service will expose
      targetPort: 8000 # The port on the pod that the Service should forward traffic to
      nodePort: 30001 # The port on each Node on which this service is exposed
